org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.209
loader_version_range=[1,)

mod_id=quark_ponders
mod_name=QuarkPonders
mod_license=GNU LGPL 3.0
mod_version=1.4
mod_group_id=com.leobeliik
mod_authors=LeoBeliik
mod_description=Ponder for Quark mod.

quark_version=4.1-475
zeta_version=1.1-39-+
ponder_version=1.0.81+mc1.21.1
flywheel_version=1.0.4
jei_version=19.+